# Generated by Django 4.0.5 on 2022-12-09 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('Category_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Category_Name', models.CharField(max_length=100)),
                ('Category_Desc', models.CharField(max_length=100)),
                ('Category_ParentID', models.FloatField()),
                ('Category_IsActive', models.BooleanField(blank=True, default=True, null=True)),
                ('Category_CreatedAt', models.DateTimeField(blank=True, null=True)),
                ('Category_ModifiedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('Competitor_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Competitor_Name', models.CharField(max_length=100)),
                ('Competitor_SalePrice', models.FloatField()),
                ('Competitor_AvailableProducts', models.FloatField()),
                ('Competitor_Reviews', models.CharField(max_length=100)),
                ('Competitor_Rating', models.CharField(max_length=100)),
                ('Competitor_Brand', models.CharField(max_length=100)),
                ('Competitor_ASIN', models.FloatField()),
                ('Competitor_UPC', models.FloatField()),
                ('Competitor_Desc', models.CharField(max_length=100)),
                ('Competitor_Quantity', models.FloatField()),
                ('Competitor_UnitPrice', models.FloatField()),
                ('Competitor_Variance', models.FloatField()),
                ('Competitor_IsActive', models.BooleanField(blank=True, default=True, null=True)),
                ('Competitor_CreatedAt', models.DateTimeField(blank=True, null=True)),
                ('Competitor_ModifiedAt', models.DateTimeField(blank=True, null=True)),
                ('Competitor_DateJoined', models.DateTimeField(blank=True, null=True)),
                ('Competitor_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller_dashboard.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Crawl',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('Crawl_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Crawl_Time', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('Dept_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Dept_Name', models.CharField(max_length=100)),
                ('Dept_Desc', models.CharField(max_length=100)),
                ('Dept_IsActive', models.BooleanField(blank=True, default=True, null=True)),
                ('Dept_CreatedAt', models.DateTimeField(blank=True, null=True)),
                ('Dept_ModifiedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('Loc_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Loc_Code', models.CharField(max_length=100)),
                ('Loc_Name', models.CharField(max_length=100)),
                ('Loc_Zip', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('PRD_ID', models.FloatField()),
                ('PRD_Name', models.CharField(max_length=100)),
                ('PRD_Desc', models.CharField(max_length=256)),
                ('PRD_Unit', models.FloatField()),
                ('PRD_UoM', models.FloatField()),
                ('PRD_URL', models.CharField(max_length=256)),
                ('PRD_UPC', models.CharField(max_length=100)),
                ('PRD_ASIN', models.CharField(max_length=100)),
                ('PRD_MRP', models.FloatField()),
                ('PRD_Brand', models.CharField(max_length=100)),
                ('PRD_Image1', models.BinaryField()),
                ('PRD_Image2', models.BinaryField()),
                ('PRD_Image3', models.BinaryField()),
                ('PRD_Variance', models.CharField(max_length=100)),
                ('PRD_IsActive', models.BooleanField(blank=True, default=True, null=True)),
                ('PRD_CreatedAt', models.DateTimeField(blank=True, null=True)),
                ('PRD_ModifiedAt', models.DateTimeField(blank=True, null=True)),
                ('PRD_Competitor_BestLink', models.CharField(max_length=256)),
                ('Category_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller_dashboard.category')),
                ('Competitor_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller_dashboard.competitor')),
                ('Crawl_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller_dashboard.crawl')),
                ('Dept_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller_dashboard.department')),
                ('Location_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller_dashboard.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('Seller_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Seller_Name', models.CharField(max_length=100)),
                ('Loc_ID', models.FloatField()),
                ('Seller_Rating', models.CharField(max_length=100)),
                ('Seller_Review', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('Store_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Store_Name', models.CharField(max_length=100)),
                ('Loc_ID', models.FloatField()),
                ('Store_Rating', models.CharField(max_length=100)),
                ('Store_Review', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('User_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('User_Name', models.CharField(max_length=100)),
                ('User_Email', models.CharField(max_length=100)),
                ('User_PWD', models.CharField(max_length=100)),
                ('User_Mobile', models.FloatField()),
                ('User_EmailVerified', models.BooleanField(blank=True, default=True, null=True)),
                ('User_EmailVeriCode', models.CharField(max_length=100)),
                ('User_MobVerified', models.BooleanField(blank=True, default=True, null=True)),
                ('User_MobileVeriCode', models.CharField(max_length=100)),
                ('User_Grp_ID', models.FloatField()),
                ('User_IsActive', models.BooleanField(blank=True, default=True, null=True)),
                ('User_CreatedAt', models.DateTimeField(blank=True, null=True)),
                ('User_ModifiedAt', models.DateTimeField(blank=True, null=True)),
                ('User_DateJoined', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('website_url', models.CharField(max_length=256)),
                ('vendor_image', models.URLField(default='https://www.freeiconspng.com/uploads/no-image-icon-6.png')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawCrawledData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller_dashboard.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='Seller_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller_dashboard.seller'),
        ),
        migrations.AddField(
            model_name='product',
            name='Store_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller_dashboard.store'),
        ),
        migrations.AddField(
            model_name='product',
            name='User_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller_dashboard.user'),
        ),
        migrations.CreateModel(
            name='ErrorLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=512)),
                ('crawl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller_dashboard.rawcrawleddata')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
